apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: simple1
      app.kubernetes.io/component: simple1
      app.kubernetes.io/instance: simple1
    name: simple1
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: simple1
      app.kubernetes.io/component: simple1
      app.kubernetes.io/instance: simple1
    name: simple1
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: simple1:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: https://github.com/kiranchavala/simpleapp
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: php:7.4-ubi8
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: DBWUMmAz9Kpajja6gGXW
      type: GitHub
    - generic:
        secret: 0LVs_48XlWvjhWnRBEb3
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"simple1:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"simple1\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: simple1
      app.kubernetes.io/component: simple1
      app.kubernetes.io/instance: simple1
    name: simple1
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: simple1
    strategy: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: simple1
      spec:
        containers:
        - image: ' '
          name: simple1
          ports:
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          resources: {}
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: simple1
      app.kubernetes.io/component: simple1
      app.kubernetes.io/instance: simple1
    name: simple1
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      deployment: simple1
  status:
    loadBalancer: {}
kind: List
metadata: {}
